const mongoose = require("mongoose"),
    config = require("../default-settings.json");

const SettingsSchema = new mongoose.Schema({
    websiteName: String,
    websiteSubtitle: String,
    landingText: String,
    faq: String,
    resourceLinks: Array,
    resourceTitles: Array,
    mailerEmail: String,
    mailerPassword: String,
    websiteLogo: String,
    carouselImages: Array,
    carouselTitles: Array,
    modlistURL: String,
    a3unitsURL: String,
    steamgroupURL: String,
    donateURL: String,
    ts3URL: String,
    discordURL: String,
    youtubeURL: String,
    instagramURL: String,
    enableApplication: String,
    enableCallToAction: String,
    enableRetiredMembers: String,
    enableEventRegistration: String,
    companies: Array,
    platoons: Array,
    squads: Array,
    teams: Array,
    sShops: Array,
    ranks: Array,
    roles: Array,
    tabs: Array,
    tabDesc: Array,
    certifications: Array,
    awards: Array,
    awardDesc: Array,
    userGroups: Array,
    enableVisibility: String,
});

module.exports = mongoose.model("Settings", SettingsSchema);